version: '2'
services:

  app-api:
    image: "node:7.2.1"
    working_dir: /usr/src/api
    command: ./run-dev.sh
    volumes:
     - ./api:/usr/src/api
     - /usr/src/api/node_modules

  app-ui:
    image: "node:7.2.1"
    working_dir: /usr/src/ui
    command: ./run-dev.sh
    volumes:
     - ./ui:/usr/src/ui
     - /usr/src/ui/node_modules

  nginx:
    image: nginx
    ports:
     - "80:80"
    volumes:
     - ./proxy/conf.d:/etc/nginx/conf.d
    depends_on:
     - app-ui
     - app-api
